name = "bushwp/contracts"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'bushwp/contracts'"

[repository]
user = "bushwp"
project = "contracts"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
